common: &common
  host: localhost
  adapter: postgresql
  username: motta
  password: "" # from psql setup, see Postgresql

development:
  <<: *common
  database: sniffer_dev

test:
  <<: *common
  database: sniffer_test

production:
  <<: *common
  database: sniffer
